### ISSUE TITLE
Lose of data.

### ISSUE THREAD

**Issue by onobrain** [wizardion/chrome-notes#44]
In case of an update, do I lose all my previous data. is there any way to prevent such thing.

**Comment by wizardion** [comment]
In case of any updates, you should not lose any data. All data should be migrated from the LocalStorage to the new IndexedDB storage. If you think you have lost your data, please provide more details...
1. Did you get the What's New page once the app is updated?
   - If so, please open the Options page and navigate to the additional params `?develop=tue`. Then enable the Development section and print all data by clicking the appropriate link, Be sure that the Dev panel is opened and the Console tab is selected.
   - If you haven't seen this page, please open it from the Options page, link is located at the bottom. 

Please be sure you have the latest version installed, the current version is 2.1.1 which contains a fix when the sync process was working incorrectly.

**Comment by wizardion** [comment]
@onobrain Hi, do you have any updates on your issue? 

The reason I'm asking is if you have trouble with data lost in the new version, and you indeed think you've lost some notes, you have only 3 days from the moment it happened, then it will be erased, see the option below...

---
<img width="343" alt="Screenshot 2024-06-20 at 7 35 38 AM" src="https://github.com/wizardion/chrome-notes/assets/2981194/03688fab-9a55-4404-ae15-c18b138f4ef3">
